export const ROLES = {
  CUSTOMER: 'CUSTOMER',
  ADMIN: 'ADMIN',
  SALES_STAFF: 'SALES_STAFF',
  SERVICE_STAFF: 'SERVICE_STAFF',
  SUPER_ADMIN: 'SUPER_ADMIN',
};

export const ENQUIRY_STATUS = {
  NEW: 'NEW',
  CONTACTED: 'CONTACTED',
  FOLLOW_UP: 'FOLLOW_UP',
  CONVERTED: 'CONVERTED',
  CLOSED: 'CLOSED',
};

export const QUOTE_STATUS = {
  PENDING: 'PENDING',
  QUOTE_SENT: 'QUOTE_SENT',
  ACCEPTED: 'ACCEPTED',
  REJECTED: 'REJECTED',
  CLOSED: 'CLOSED',
};

export const SERVICE_TYPES = {
  INSTALLATION: 'INSTALLATION',
  REPAIR: 'REPAIR',
  MAINTENANCE: 'MAINTENANCE',
  WARRANTY_SERVICE: 'WARRANTY_SERVICE',
  TECH_SUPPORT: 'TECH_SUPPORT',
};

export const SERVICE_STATUS = {
  REQUESTED: 'REQUESTED',
  ASSIGNED: 'ASSIGNED',
  SCHEDULED: 'SCHEDULED',
  IN_PROGRESS: 'IN_PROGRESS',
  COMPLETED: 'COMPLETED',
  CANCELLED: 'CANCELLED',
};

export const WARRANTY_STATUS = {
  ACTIVE: 'ACTIVE',
  EXPIRED: 'EXPIRED',
  VOID: 'VOID',
  CLAIMED: 'CLAIMED',
};

export const CLAIM_STATUS = {
  FILED: 'FILED',
  IN_REVIEW: 'IN_REVIEW',
  APPROVED: 'APPROVED',
  REJECTED: 'REJECTED',
  RESOLVED: 'RESOLVED',
};

export const ORDER_STATUS = {
  PENDING: 'PENDING',
  CONFIRMED: 'CONFIRMED',
  PROCESSING: 'PROCESSING',
  SHIPPED: 'SHIPPED',
  DELIVERED: 'DELIVERED',
  CANCELLED: 'CANCELLED',
  REFUNDED: 'REFUNDED',
};

export const PAYMENT_STATUS = {
  PENDING: 'PENDING',
  PAID: 'PAID',
  FAILED: 'FAILED',
  REFUNDED: 'REFUNDED',
};

export const STOCK_STATUS = {
  IN_STOCK: 'IN_STOCK',
  LOW_STOCK: 'LOW_STOCK',
  OUT_OF_STOCK: 'OUT_OF_STOCK',
  PRE_ORDER: 'PRE_ORDER',
};
